In [1]:
#importing some useful packages
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import cv2
%matplotlib inline

In [4]:
img = cv2.imread('test_images/solidWhiteRight.jpg')
gray_img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

ret,thresh = cv2.threshold(gray_img,127,255,0)
_, contours,hierarchy = cv2.findContours(thresh, 1, 2)

cnt = contours[0]
print(cnt)

[[[959 538]]

 [[958 539]]

 [[959 539]]]
